
let USA = {
    auction: {
        COPART: {
            location: {
                GA: {
                    value_0: ['APPLETON - WI', 925],
                    value_1: ['ATLANTA EAST - GA', 500],
                    value_2: ['ATLANTA NORTH - GA', 500],
                    value_3: ['ATLANTA SOUTH - GA', 500],
                    value_4: ['ATLANTA WEST - GA', 500],
                    value_5: ['AUGUSTA - GA', 475],
                    value_6: ['BATON ROUGE - LA', 600],
                    value_7: ['BIRMINGHAM - AL', 575],
                    value_8: ['CARTERSVILLE - GA', 500],
                    value_9: ['CHARLESTON - SC', 425],
                    value_10: ['CHINA GROVE - NC', 475],
                    value_11: ['COLORADO SPRINGS - COCOLUMBIA - MO', 800],
                    value_12: ['COLUMBIA - SC', 400],
                    value_13: ['CONCORD - NC', 475],
                    value_14: ['CRASHEDTOYS ATLANTA', 450],
                    value_15: ['DANVILLE - VA', 600],
                    value_16: ['DOTHAN - AL', 550],
                    value_17: ['DYER - IN', 800],
                    value_18: ['EARLINGTON - KY', 725],
                    value_19: ['FAIRBURN - GA', 475],
                    value_20: ['FT.PIERCE - FL', 550],
                    value_21: ['GASTONIA - NC', 475],
                    value_22: ['GREER - SC', 475],
                    value_23: ['INDIANAPOLIS - IN', 800],
                    value_24: ['JACKSON - MS', 575],
                    value_25: ['JACKSONVILLE EAST - FL', 400],
                    value_26: ['JACKSONVILLE NORTH -FL', 400],
                    value_27: ['JACKSONVILLE WEST - FL', 400],
                    value_28: ['KANSAS CITY - KS', 825],
                    value_29: ['KANSAS CITY EAST', 825],
                    value_30: ['KNOXVILLE - TN', 575],
                    value_31: ['LEXINGTON EAST - KY', 725],
                    value_32: ['LEXINGTON WEST - KY', 725],
                    value_33: ['LITTLE ROCK - AR', 650],
                    value_34: ['LOS ANGELES - CALOUISVILLE - KY', 725],
                    value_35: ['LUMBERTON - NC', 500],
                    value_36: ['MACON - GA', 450],
                    value_37: ['MADISON - WI', 875],
                    value_38: ['MADISON SOUTH - WI', 875],
                    value_39: ['MEBANE - NC', 500],
                    value_40: ['MEMPHIS - TN', 700],
                    value_41: ['MIAMI CENTRAL - FL', 550],
                    value_42: ['MIAMI NORTH - FL', 550],
                    value_43: ['MIAMI SOUTH - FL', 550],
                    value_44: ['MINNEAPOLIS - MN', 1150],
                    value_45: ['MINNEAPOLIS NORTH - MN', 1150],
                    value_46: ['MOBILE - AL', 525],
                    value_47: ['MOBILE SOUTH - AL', 525],
                    value_48: ['MOCKSVILLE - NC', 500],
                    value_49: ['MONTGOMERY - AL', 575],
                    value_50: ['NASHVILLE - TN', 600],
                    value_51: ['NEW ORLEANS - LA', 600],
                    value_52: ['NORTH CHARLESTON', 425],
                    value_53: ['OCALA - FL', 500],
                    value_54: ['ORLANDO - FL', 500],
                    value_55: ['ORLANDO NORTH - FL', 500],
                    value_56: ['ORLANDO SOUTH - FL', 500],
                    value_57: ['PUNTA GORDA - FL', 525],
                    value_58: ['PUNTA GORDA SOUTH - FL', 525],
                    value_59: ['RALEIGH - NC', 500],
                    value_60: ['RALEIGH NORTH - NC', 500],
                    value_61: ['SAVANNAH - GA', 325],
                    value_62: ['SIKESTON - MO', 800],
                    value_63: ['SOUTHERN ILLINOIS - IL', 775],
                    value_64: ['SPARTANBURG - SC', 500],
                    value_65: ['SPOKANE - WASPRINGFIELD - MO', 800],
                    value_66: ['ST. LOUIS - MO', 800],
                    value_67: ['TALLAHASSEE - FL', 500],
                    value_68: ['TAMPA SOUTH - FL', 500],
                    value_69: ['TANNER - AL', 600],
                    value_70: ['TIFTON - GA', 450],
                    value_71: ['WALTON - KY', 725],
                    value_72: ['WEST PALM BEACH - FL', 550]
                },
                CA: {
                    value_0: ['ADELANTO - CA', 425],
                    value_1: ['ALBUQUERQUE - NM', 900],
                    value_2: ['ANTELOPE - CA', 550],
                    value_3: ['BAKERSFIELD - CA', 450],
                    value_4: ['COLORADO SPRINGS - COCOLUMBIA - MO', 875],
                    value_5: ['CRASHEDTOYS SACRAMENTO - CA', 550],
                    value_6: ['DENVER - CO', 875],
                    value_7: ['DENVER CENTRAL - CO', 875],
                    value_8: ['DENVER SOUTH - CO', 875],
                    value_9: ['EUGENE - OR', 850],
                    value_10: ['FREMONT - CA', 550],
                    value_11: ['FRESNO - CA', 475],
                    value_12: ['HAYWARD - CA', 550],
                    value_13: ['HONOLULU - HI', 1900],
                    value_14: ['LAS VEGAS - NV', 525],
                    value_15: ['LONG BEACH - CA', 340],
                    value_16: ['LOS ANGELES - CALOUISVILLE - KY', 340],
                    value_17: ['MARTINEZ - CA', 550],
                    value_18: ['OGDEN- UT', 650],
                    value_19: ['PASCO - WA', 950],
                    value_20: ['PHOENIX - AZ', 500],
                    value_21: ['PORTLAND NORTH - OR', 800],
                    value_22: ['PORTLAND SOUTH - OR', 800],
                    value_23: ['RANCHO CUCAMONGA - CA', 390],
                    value_24: ['REDDING - CA', 725],
                    value_25: ['RENO - NV', 625],
                    value_26: ['SACRAMENTO - CA', 550],
                    value_27: ['SALT LAKE CITY - UT', 650],
                    value_28: ['SAN BERNARDINO- CA', 400],
                    value_29: ['SAN DIEGO - CA', 425],
                    value_30: ['SAN JOSE - CA', 550],
                    value_31: ['SO SACRAMENTO - CA', 525],
                    value_32: ['SPOKANE - WASPRINGFIELD - MO', 950],
                    value_33: ['SUN VALLEY - CA', 375],
                    value_34: ['TUCSON - AZ', 575],
                    value_35: ['VALLEJO - CA', 575],
                    value_36: ['VAN NUYS - CA', 380]
                },
                NY: {
                    value_0: ['ALBANY - NY', 450],
                    value_1: ['ALTOONA - PA', 625],
                    value_2: ['BALTIMORE - MD', 500],
                    value_3: ['BALTIMORE EAST-MD', 500],
                    value_4: ['BUFFALO - NY', 675],
                    value_5: ['CANDIA - NH', 575],
                    value_6: ['CHAMBERSBURG - PA', 550],
                    value_7: ['CHARLESTON - WV', 700],
                    value_8: ['CHICAGO NORTH - IL', 775],
                    value_9: ['CHICAGO SOUTH - IL', 775],
                    value_10: ['CICERO-IN', 775],
                    value_11: ['CLEVELAND EAST - OH', 625],
                    value_12: ['CLEVELAND WEST - OH', 625],
                    value_13: ['COLUMBUS - OH', 650],
                    value_14: ['CRASHEDTOYS EAST BETHEL - MN', 800],
                    value_15: ['CRASHEDTOYS ELDRIDGE - IA', 950],
                    value_16: ['CRASHEDTOYS MINNEAPOLIS-MN', 1000],
                    value_17: ['CULPEPER - VA', 575],
                    value_18: ['DAVENPORT - IA', 800],
                    value_19: ['DAYTON - OH', 675],
                    value_20: ['DES MOINES - IA', 825],
                    value_21: ['DETROIT - MI', 725],
                    value_22: ['EXETER - RI', 525],
                    value_23: ['FLINT - MI', 700],
                    value_24: ['FORT WAYNE - IN', 800],
                    value_25: ['FREDERICKSBURG - VA', 525],
                    value_26: ['FREETOWN - MA', 550],
                    value_27: ['Freetown - MA', 550],
                    value_28: ['GLASSBORO EAST - NJ', 400],
                    value_29: ['GLASSBORO WEST-NJ', 400],
                    value_30: ['HAMMOND - IN', 800],
                    value_31: ['HAMPTON - VA', 550],
                    value_32: ['HARRISBURG - PA', 450],
                    value_33: ['HARTFORD - CT', 425],
                    value_34: ['HARTFORD SPRINGFIELD-CT', 425],
                    value_35: ['INDIANAPOLIS - IN', 800],
                    value_36: ['IONIA - MI', 850],
                    value_37: ['KINCHELOE - MI', 1175],
                    value_38: ['LANSING - MI', 850],
                    value_39: ['LINCOLN - NE', 800],
                    value_40: ['LONG ISLAND - NY', 450],
                    value_41: ['LYMAN - ME', 650],
                    value_42: ['MILWAUKEE - WI', 850],
                    value_43: ['MILWAUKEE NORTH-WI', 850],
                    value_44: ['MILWAUKEE SOUTH - WI', 850],
                    value_45: ['MINNEAPOLIS - MN', 875],
                    value_46: ['MINNEAPOLIS NORTH - MN', 875],
                    value_47: ['NEWBURGH - NY', 450],
                    value_48: ['NORTH BOSTON - MA', 525],
                    value_49: ['PEORIA - IL', 800],
                    value_50: ['PHILADELPHIA - PA', 430],
                    value_51: ['PHILADELPHIA EAST', 430],
                    value_52: ['PHILADELPHIA EAST - SUBLOT - PA', 430],
                    value_53: ['PITTSBURG SOUTH - PA', 625],
                    value_54: ['PITTSBURGH EAST - PA', 650],
                    value_55: ['PITTSBURGH NORTH - PA', 650],
                    value_56: ['PITTSBURGH WEST - PA', 650],
                    value_57: ['RICHMOND - VA', 575],
                    value_58: ['RICHMOND EAST-VA', 575],
                    value_59: ['ROCHESTER - NY', 600],
                    value_60: ['SCRANTON - PA', 475],
                    value_61: ['SEAFORD - DE', 500],
                    value_62: ['SOMERVILLE - NJ', 375],
                    value_63: ['SOUTH BOSTON - MA', 550],
                    value_64: ['ST. CLOUD - MN', 900],
                    value_65: ['SYRACUSE - NY', 525],
                    value_66: ['TORONTO CANADA', 1200],
                    value_67: ['TRENTON - NJ', 400],
                    value_68: ['WASHINGTON DC - MD', 500],
                    value_69: ['WEST WARREN - MA', 525],
                    value_70: ['WHEELING - IL', 700],
                    value_71: ['YORK HAVEN - PA', 475]
                },
                TX: {
                    value_0: ['ALBUQUERQUE - NM', 900],
                    value_1: ['AMARILLO - TX', 625],
                    value_2: ['ANDREWS-TX', 650],
                    value_3: ['AUSTIN - TX', 475],
                    value_4: ['COLORADO SPRINGS - COCOLUMBIA - MO', 900],
                    value_5: ['CORPUS CHRISTI - TX', 450],
                    value_6: ['CRASHEDTOYS DALLAS- TX', 450],
                    value_7: ['DALLAS - TX', 475],
                    value_8: ['DALLAS SOUTH - TX', 475],
                    value_9: ['EL PASO - TX', 650],
                    value_10: ['FAYETTEVILLE - AR', 675],
                    value_11: ['FT.WORTH - TX', 475],
                    value_12: ['HOUSTON - TX', 400],
                    value_13: ['HOUSTON EAST-TX', 400],
                    value_14: ['LONGVIEW - TX', 475],
                    value_15: ['LUFKIN - TX', 425],
                    value_16: ['MCALLEN - TX', 475],
                    value_17: ['OKLAHOMA CITY - OK', 625],
                    value_18: ['SAN ANTONIO - TX', 475],
                    value_19: ['SHREVEPORT - LA', 500],
                    value_20: ['TULSA - OK', 675],
                    value_21: ['WACO - TX', 475],
                    value_22: ['WICHITA - KS', 675]
                },
                WA: {
                    value_0: ['ANCHORAGE - AK', 2050],
                    value_1: ['BILLINGS - MT', 1000],
                    value_2: ['BISMARCK - ND', 1500],
                    value_3: ['BOISE - ID', 675],
                    value_4: ['CASPER - WY', 1500],
                    value_5: ['EUGENE - OR', 575],
                    value_6: ['GRAHAM - WA', 350],
                    value_7: ['HELENA - MT', 900],
                    value_8: ['NORTH SEATTLE - WA', 390],
                    value_9: ['PASCO - WA', 550],
                    value_10: ['PORTLAND NORTH - OR', 475],
                    value_11: ['PORTLAND SOUTH - OR', 475],
                    value_12: ['SPOKANE - WASPRINGFIELD - MO', 525]
                }
            }
        },
        IAAI: {
            location: {
                GA: {
                    value_0: ['ADESA BIRMINGHAM - AL', 550],
                    value_1: ['APPLETON - WI', 925],
                    value_2: ['ASHEVILLE - NC', 525],
                    value_3: ['ASHLAND - KY', 900],
                    value_4: ['ATLANTA - GA', 500],
                    value_5: ['ATLANTA EAST - GA', 500],
                    value_6: ['ATLANTA NORTH - GA', 500],
                    value_7: ['ATLANTA SOUTH - GA', 500],
                    value_8: ['BATON ROUGE - LA', 600],
                    value_9: ['BIRMINGHAM - AL', 575],
                    value_10: ['BIRMINGHAM - BLENDED SALES - AL', 500],
                    value_11: ['BOWLING GREEN - KY', 750],
                    value_12: ['CHARLESTON - SC', 425],
                    value_13: ['CHARLOTTE - NC', 500],
                    value_14: ['CHATTANOOGA - TN', 625],
                    value_15: ['CLEARWATER - FL', 500],
                    value_16: ['COLUMBIA - SC', 400],
                    value_17: ['CONCORD - NC', 475],
                    value_18: ['DOTHAN - AL', 550],
                    value_19: ['FORT MYERS - FL', 550],
                    value_20: ['FT.PIERCE - FL', 550],
                    value_21: ['GREENSBORO - NC', 525],
                    value_22: ['GREENVILLE - SC', 500],
                    value_23: ['GRENADA - MS', 650],
                    value_24: ['GULF COAST - MS', 525],
                    value_25: ['HUNTSVILLE - AL', 575],
                    value_26: ['INDIANAPOLIS - IN', 800],
                    value_27: ['INDIANAPOLIS SOUTH - IN', 800],
                    value_28: ['JACKSON - MS', 575],
                    value_29: ['JACKSONVILLE - FL', 400],
                    value_30: ['KANSAS CITY - KS', 825],
                    value_31: ['KANSAS CITY EAST', 825],
                    value_32: ['KNOXVILLE - TN', 575],
                    value_33: ['LAFAYETTE - LA', 575],
                    value_34: ['LEXINGTON - SC', 390],
                    value_35: ['LITTLE ROCK - AR', 650],
                    value_36: ['LOUISVILLE - KY', 725],
                    value_37: ['LOUISVILLE NORTH - KY', 725],
                    value_38: ['MACON - GA', 450],
                    value_39: ['MEMPHIS - TN', 700],
                    value_40: ['MIAMI - FL', 550],
                    value_41: ['MIAMI NORTH - FL', 550],
                    value_42: ['MINNEAPOLIS/SOUTH - MN', 1150],
                    value_43: ['MINNEAPOLIS/ST.PAUL - MN', 1150],
                    value_44: ['NASHVILLE - BLENDED SALES - TN', 600],
                    value_45: ['NASHVILLE - TN', 600],
                    value_46: ['NEW ORLEANS - LA', 600],
                    value_47: ['NEW ORLEANS AND LOUISIANA FLOOD', 600],
                    value_48: ['NEW ORLEANS EAST - LA', 600],
                    value_49: ['ORLANDO - FL', 500],
                    value_50: ['ORLANDO NORTH - FL', 500],
                    value_51: ['PADUCAH - KY', 775],
                    value_52: ['PENSACOLA - FL', 525],
                    value_53: ['PORTAGE - WI', 1175],
                    value_54: ['PULASKI - VA', 625],
                    value_55: ['RALEIGH - NC', 500],
                    value_56: ['SAVANNAH - GA', 325],
                    value_57: ['SPRINGFIELD - MO', 800],
                    value_58: ['ST. LOUIS - IL', 800],
                    value_59: ['TAMPA - FL', 500],
                    value_60: ['TAMPA NORTH - FL', 500],
                    value_61: ['TIFTON - GA', 450],
                    value_62: ['WEST PALM BEACH - FL', 550],
                    value_63: ['WILMINGTON - NC', 525]
                },
                CA: {
                    value_0: ['ACE - PERRIS 2 - CA', 400],
                    value_1: ['ACE CARSON - CA', 350],
                    value_2: ['ACE-PERRIS', 400],
                    value_3: ['ALBUQUERQUE - NM', 900],
                    value_4: ['ANAHEIM - CA', 360],
                    value_5: ['COLORADO SPRINGS - CO', 875],
                    value_6: ['COLTON - CA', 390],
                    value_7: ['DENVER - CO', 875],
                    value_8: ['DENVER EAST - CO', 875],
                    value_9: ['EAST BAY - CA', 550],
                    value_10: ['EUGENE - OR', 850],
                    value_11: ['FONTANA - CA', 390],
                    value_12: ['FREDERICKSBURG-SOUTH - VAFREMONT - CA', 550],
                    value_13: ['FRESNO - CA', 475],
                    value_14: ['HIGH DESERT - CA', 425],
                    value_15: ['HONOLULU - HI', 1900],
                    value_16: ['LAS VEGAS - NV', 525],
                    value_17: ['LOS ANGELES - CA', 340],
                    value_18: ['LOS ANGELES SOUTH - CA', 340],
                    value_19: ['NORTH HOLLYWOOD - CA', 380],
                    value_20: ['PHOENIX - AZ', 500],
                    value_21: ['PORTLAND - OR', 800],
                    value_22: ['PORTLAND NORTH - OR', 800],
                    value_23: ['PORTLAND WEST - OR', 800],
                    value_24: ['RENO - NV', 625],
                    value_25: ['SACRAMENTO - CA', 550],
                    value_26: ['SALT LAKE CITY - UT', 650],
                    value_27: ['SAN DIEGO - CA', 425],
                    value_28: ['SPOKANE - WA', 950],
                    value_29: ['TUCSON - AZ', 575],
                    value_30: ['WESTERN COLORADO - CO', 1100]
                },
                NY: {
                    value_0: ['ACRON CANTON - OH', 675],
                    value_1: ['ALBANY - NY', 450],
                    value_2: ['ALTOONA - PA', 625],
                    value_3: ['AVENEL - NJ', 350],
                    value_4: ['BALTIMORE - MD', 500],
                    value_5: ['BOSTON-SHIRLEY - MA', 550],
                    value_6: ['BRIDGEPORT - PA', 450],
                    value_7: ['BUCKHANNON - WV', 700],
                    value_8: ['BUFFALO - NY', 675],
                    value_9: ['BURLINGTON - VT', 700],
                    value_10: ['CENTRAL NEW JERSEY - NJ', 375],
                    value_11: ['CHICAGO NORTH - IL', 775],
                    value_12: ['CHICAGO SOUTH - IL', 775],
                    value_13: ['CHICAGO WEST - IL', 725],
                    value_14: ['CINCINNATI - OH', 650],
                    value_15: ['CINCINNATI SOUTH - OH', 650],
                    value_16: ['CLEVELAND - OH', 625],
                    value_17: ['COLUMBUS - OH', 650],
                    value_18: ['CULPEPER - VA', 575],
                    value_19: ['DAVENPORT - IA', 800],
                    value_20: ['DAYTON - OH', 675],
                    value_21: ['DES MOINES - IA', 825],
                    value_22: ['DETROIT - MI', 725],
                    value_23: ['DUNDALK - MD', 500],
                    value_24: ['ELKTON - MD', 475],
                    value_25: ['ENGLISHTOWN - NJ', 375],
                    value_26: ['ERIE - PA', 675],
                    value_27: ['FARGO - ND', 1300],
                    value_28: ['FLINT - MI', 700],
                    value_29: ['FREDERICKSBURG-SOUTH - VAFREMONT - CA', 525],
                    value_30: ['Fredericksburg-South - VA', 475],
                    value_31: ['GRAND RAPIDS - MI', 850],
                    value_32: ['HARTFORD SOUTH - CT', 425],
                    value_33: ['HARTFORD - CT', 425],
                    value_34: ['INDIANAPOLIS - IN', 800],
                    value_35: ['INDIANAPOLIS SOUTH - IN', 800],
                    value_36: ['LAUREL - MD', 500],
                    value_37: ['LINCOLN - IL', 825],
                    value_38: ['LONG ISLAND - NY', 450],
                    value_39: ['MANCHESTER - NH', 575],
                    value_40: ['METRO - DC', 500],
                    value_41: ['MILWAUKEE - WI', 850],
                    value_42: ['MINNEAPOLIS/SOUTH - MN', 875],
                    value_43: ['MINNEAPOLIS/ST.PAUL - MN', 875],
                    value_44: ['NEW CASTLE - DE', 450],
                    value_45: ['NEWBURGH - NY', 450],
                    value_46: ['NOTHERN NEW JERSEY - NJ', 360],
                    value_47: ['NOTHERN VIRGINIA - VA', 525],
                    value_48: ['OMAHA - NE', 850],
                    value_49: ['PHILADELPHIA - PA', 430],
                    value_50: ['PITTSBURGH - PA', 650],
                    value_51: ['PITTSBURGH NORTH - PA', 650],
                    value_52: ['PORT MURRAY - NJ', 425],
                    value_53: ['PORTAGE - WI', 825],
                    value_54: ['PORTLAND GORHAM - ME', 625],
                    value_55: ['PROVIDENCE - RI', 525],
                    value_56: ['PULASKI - VA', 625],
                    value_57: ['Port Murray - NJ', 400],
                    value_58: ['RICHMOND - VA', 575],
                    value_59: ['ROANOKE - VA', 625],
                    value_60: ['ROCHESTER - NY', 600],
                    value_61: ['ROCHESTER WEST - NY', 600],
                    value_62: ['SAYREVILLE - NJ', 360],
                    value_63: ['SCRANTON - PA', 475],
                    value_64: ['SHADY SPRING - WV', 675],
                    value_65: ['SIOUX FALLS - SD', 1200],
                    value_66: ['SOUTH BEND - IN', 775],
                    value_67: ['SOUTHERN NEW JERSEY - NJ', 400],
                    value_68: ['SUFFOLK - VA', 550],
                    value_69: ['SYRACUSE - NY', 525],
                    value_70: ['TAUNTON - MA', 525],
                    value_71: ['TEMPLETON-MA', 550],
                    value_72: ['TIDEWATER - VA', 525],
                    value_73: ['YORK SPRINGS - PA', 475]
                },
                TX: {
                    value_0: ['ALBUQUERQUE - NM', 900],
                    value_1: ['AMARILLO - TX', 625],
                    value_2: ['AUSTIN - TX', 475],
                    value_3: ['COLORADO SPRINGS - CO', 900],
                    value_4: ['CORPUS CHRISTI - TX', 450],
                    value_5: ['DALLAS - TX', 475],
                    value_6: ['DALLAS / FT. WORTH - TX', 475],
                    value_7: ['EL PASO - TX', 650],
                    value_8: ['FAYETTEVILLE - AR', 675],
                    value_9: ['FORT WORTH NORTH - TX', 475],
                    value_10: ['HOUSTON - TX', 400],
                    value_11: ['HOUSTON NORTH - TX', 400],
                    value_12: ['HOUSTON SOUTH', 400],
                    value_13: ['HOUSTON SOUTH - TX', 400],
                    value_14: ['LONGVIEW - TX', 475],
                    value_15: ['LUBBOCK - TX', 675],
                    value_16: ['MCALLEN - TX', 475],
                    value_17: ['OKLAHOMA CITY - OK', 625],
                    value_18: ['PERMIAN BASIN - TX', 575],
                    value_19: ['SAN ANTONIO - TX', 475],
                    value_20: ['SAN ANTONIO SOUTH - TX', 475],
                    value_21: ['SHREVEPORT - LA', 500],
                    value_22: ['TULSA - OK', 675],
                    value_23: ['WESTERN COLORADO - CO', 1050],
                    value_24: ['WICHITA - KS', 675]
                },
                WA: {
                    value_0: ['ANCHORAGE - AK', 2050],
                    value_1: ['BILLINGS - MT', 1000],
                    value_2: ['BOISE - ID', 675],
                    value_3: ['CASPER - WY', 1500],
                    value_4: ['EUGENE - OR', 575],
                    value_5: ['MISSOULA - MT', 850],
                    value_6: ['PORTLAND - OR', 450],
                    value_7: ['PORTLAND NORTH - OR', 475],
                    value_8: ['PORTLAND WEST - OR', 475],
                    value_9: ['SEATLE - WA', 350],
                    value_10: ['SEATLE SOUTH - WA', 350],
                    value_11: ['SPOKANE - WA', 525]
                }
            }
        },
        Mannheim:{
            location: {
                GA: {
                    value_0: ['ATLANTA - GA', 500],
                    value_1: ['BIRMINGHAM - AL', 575],
                    value_2: ['CHARLOTTE - NC', 500],
                    value_3: ['CLEARWATER - FL', 500],
                    value_4: ['DARLINGTON - SC', 500],
                    value_5: ['DAYTONA BEACH - FL', 500],
                    value_6: ['FORT LAUDERDALE - FL', 550],
                    value_7: ['FORT MYERS - FL', 550],
                    value_8: ['GREER - SC', 475],
                    value_9: ['INDIANAPOLIS - IN', 800],
                    value_10: ['JACKSONVILLE - FL', 400],
                    value_11: ['KANSAS CITY - KS', 825],
                    value_12: ['LAFAYETTE - LA', 575],
                    value_13: ['LAKELAND - FL', 625],
                    value_14: ['LITTLE ROCK - AR', 650],
                    value_15: ['LOUISVILLE - IN', 725],
                    value_16: ['MANHEIM ARENA ILLINOIS - IL', 775],
                    value_17: ['MANHEIM CENTRAL FLORIDA - FL', 500],
                    value_18: ['MANHEIM GEORGIA - GA', 500],
                    value_19: ['MANHEIM KANSAS CITY - MO', 825],
                    value_20: ['MANHEIM METRO ATLANTA', 500],
                    value_21: ['MANHEIM MISSISSIPPI - MS', 550],
                    value_22: ['MANHEIM NORTH CAROLINA - NC', 500],
                    value_23: ['MINNEAPOLIS - MN', 1150],
                    value_24: ['MONTGOMERY - AL', 575],
                    value_25: ['NASHVILLE - TN', 600],
                    value_26: ['NEW ORLEANS - LA', 600],
                    value_27: ['ORLANDO - FL', 500],
                    value_28: ['PALM BEACH - FL', 550],
                    value_29: ['PENSACOLA - FL', 525],
                    value_30: ['SPRINGFIELD - MO', 800],
                    value_31: ['ST. LOUIS - MO', 800],
                    value_32: ['ST. PETE - FL', 500],
                    value_33: ['STATESVILLE - NC', 500],
                    value_34: ['TAMPA - FL', 500],
                    value_35: ['WILMINGTON - NC', 525]
                },
                CA: {
                    value_0: ['DENVER - CO', 875],
                    value_1: ['FRESNO - CA', 475],
                    value_2: ['MANHEIM ARIZONA - AZ', 500],
                    value_3: ['MANHEIM CALIFORNIA - CA', 400],
                    value_4: ['MANHEIM CENTRAL CALIFORNIA - CA', 475],
                    value_5: ['MANHEIM HAWAII - HI', 1900],
                    value_6: ['MANHEIM NEVADA - NV', 525],
                    value_7: ['MANHEIM NEW MEXICO - NM', 750],
                    value_8: ['MANHEIM RIVERSIDE - CA', 400],
                    value_9: ['MANHEIM SAN FRANCISCO BAY - CA', 525],
                    value_10: ['MANHEIM SOUTHERN CALIFORNIA - CA', 400],
                    value_11: ['MANHEIM UTAH - UT', 625],
                    value_12: ['PHOENIX - AZ', 500],
                    value_13: ['PORTLAND - OR', 800],
                    value_14: ['SAN DIEGO - CA', 425],
                    value_15: ['TUCSON - AZ', 575]
                },
                NY: {
                    value_0: ['ALBANY - NY', 450],
                    value_1: ['CHICAGO - IL', 775],
                    value_2: ['CINCINNATI - OH', 650],
                    value_3: ['CLEVELAND - OH', 625],
                    value_4: ['CONCORD - MA', 550],
                    value_5: ['DETROIT - MI', 725],
                    value_6: ['FLINT - MI', 700],
                    value_7: ['FREDERICKSBURG - VA', 525],
                    value_8: ['HARRISONBURG - VA', 675],
                    value_9: ['INDIANAPOLIS - IN', 800],
                    value_10: ['MANHEIM BALTIMORE-WASHINGTON - M', 525],
                    value_11: ['MANHEIM IOWA - IA', 950],
                    value_12: ['MANHEIM KEYSTONE PENNSYLVANIA -', 475],
                    value_13: ['MANHEIM NEW ENGLAND - MA', 550],
                    value_14: ['MANHEIM NORTHSTAR MINNESOTA - MN', 850],
                    value_15: ['MANHEIM NY METRO SKYLINE - NJ', 400],
                    value_16: ['MANHEIM OHIO - OH', 650],
                    value_17: ['MANHEIM PENNSYLVANIA - PA', 500],
                    value_18: ['MANHEIM POPLAR BLUFF - MO', 775],
                    value_19: ['MILWAUKEE - WI', 850],
                    value_20: ['MINNEAPOLIS - MN', 875],
                    value_21: ['NEW JERSEY - NJ', 400],
                    value_22: ['NEW YORK - NY', 470],
                    value_23: ['OMAHA - NE', 850],
                    value_24: ['PHILADELPHIA - PA', 430],
                    value_25: ['PITTSBURGH - PA', 650],
                    value_26: ['ROCHESTER - NY', 600],
                    value_27: ['TORONTO CANADA', 1200]
                },
                TX: {
                    value_0: ['DALLAS - TX', 475],
                    value_1: ['DALLAS / FT. WORTH - TX', 475],
                    value_2: ['EL PASO - TX', 650],
                    value_3: ['HOUSTON - TX', 400],
                    value_4: ['MANHEIM TEXAS HOBBY - TX', 360],
                    value_5: ['OKLAHOMA CITY - OK', 625],
                    value_6: ['SAN ANTONIO - TX', 475],
                    value_7: ['TULSA - OK', 675]
                },
                WA: {
                    value_0: ['PORTLAND - OR', 450],
                    value_1: ['SEATLE - WA', 350]
                }
            }
        }
    }
};